import bayesian_problems_characterization_bayes_procedures_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace bayesian_problems_characterization_bayes_procedures_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end bayesian_problems_characterization_bayes_procedures_theorem_canonical_lane_mathlib
end HautevilleHouse
